improvements

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,7 +20,10 @@ jobs:
           cache: "npm"
 
       - name: Install dependencies
-        run: npm i
+        run: npm ci
+
+      - name: Ensure Cloudflare API Token is Set
+        run: '[ -n "$CLOUDFLARE_API_TOKEN" ] || { echo "CLOUDFLARE_API_TOKEN is missing"; exit 1; }'
 
       - name: Run OpenNext Build for Cloudflare
         run: npx opennextjs-cloudflare
